// AUTO-GENERATED by scripts/gen-blippets.ts — DO NOT EDIT.
// Source of truth: data/blippets.csv  (run: npm run gen:blippets)
import type { BlippetSpecies } from '../types/blippet';

export const SPECIES: BlippetSpecies[] = [
  {
    "dex": 1,
    "slug": "flamoo",
    "name": "Flamoo",
    "types": [
      "fire"
    ],
    "baseStats": {
      "hp": 55,
      "atk": 65,
      "def": 45,
      "spAtk": 40,
      "spDef": 50,
      "spd": 55
    },
    "rarity": "common",
    "abilities": [
      "blaze",
      "thick-hide"
    ],
    "learnset": [
      {
        "level": 1,
        "moveId": "tackle"
      },
      {
        "level": 1,
        "moveId": "ember"
      },
      {
        "level": 7,
        "moveId": "flame-charge"
      },
      {
        "level": 13,
        "moveId": "headbutt"
      }
    ],
    "movePool": [
      "tackle",
      "ember",
      "flame-charge",
      "headbutt"
    ],
    "evolution": {
      "intoSlug": "emburn",
      "level": 16
    },
    "description": "A calf with a smoldering mane. Warms its herd on cold nights.",
    "spriteKey": "blippet-flamoo",
    "sprites": {
      "front": "blippets/001_flamoo_fire.png"
    }
  },
  {
    "dex": 2,
    "slug": "mosskit",
    "name": "Mosskit",
    "types": [
      "dark",
      "grass"
    ],
    "baseStats": {
      "hp": 50,
      "atk": 55,
      "def": 40,
      "spAtk": 70,
      "spDef": 55,
      "spd": 75
    },
    "rarity": "uncommon",
    "abilities": [
      "leaf-veil",
      "keen-eye"
    ],
    "learnset": [
      {
        "level": 1,
        "moveId": "scratch"
      },
      {
        "level": 1,
        "moveId": "razor-leaf"
      },
      {
        "level": 6,
        "moveId": "shadow-sneak"
      },
      {
        "level": 12,
        "moveId": "haze"
      }
    ],
    "movePool": [
      "scratch",
      "razor-leaf",
      "shadow-sneak",
      "haze"
    ],
    "description": "A shadow-dwelling kit cloaked in moss. Glides between branches.",
    "spriteKey": "blippet-mosskit",
    "sprites": {
      "front": "blippets/002_mosskit_dark-grass.png"
    }
  },
  {
    "dex": 3,
    "slug": "axoltule",
    "name": "Axoltule",
    "types": [
      "water",
      "crystal"
    ],
    "baseStats": {
      "hp": 75,
      "atk": 50,
      "def": 80,
      "spAtk": 55,
      "spDef": 75,
      "spd": 30
    },
    "rarity": "uncommon",
    "abilities": [
      "sturdy",
      "hydration"
    ],
    "learnset": [
      {
        "level": 1,
        "moveId": "water-gun"
      },
      {
        "level": 1,
        "moveId": "harden"
      },
      {
        "level": 8,
        "moveId": "mud-shot"
      },
      {
        "level": 14,
        "moveId": "crystal-shard"
      }
    ],
    "movePool": [
      "water-gun",
      "harden",
      "mud-shot",
      "crystal-shard"
    ],
    "description": "A gentle axolotl that carries a crystal-encrusted shell drawn from cave pools.",
    "spriteKey": "blippet-axoltule",
    "sprites": {
      "front": "blippets/003_axoltule_water-crystal.png"
    }
  },
  {
    "dex": 4,
    "slug": "amerex",
    "name": "Amerex",
    "types": [
      "psychic",
      "crystal"
    ],
    "baseStats": {
      "hp": 60,
      "atk": 75,
      "def": 55,
      "spAtk": 85,
      "spDef": 60,
      "spd": 65
    },
    "rarity": "rare",
    "abilities": [
      "prism-mind",
      "crystal-armor"
    ],
    "learnset": [
      {
        "level": 1,
        "moveId": "confusion"
      },
      {
        "level": 1,
        "moveId": "crystal-shard"
      },
      {
        "level": 10,
        "moveId": "psybeam"
      },
      {
        "level": 16,
        "moveId": "prism-beam"
      }
    ],
    "movePool": [
      "confusion",
      "crystal-shard",
      "psybeam",
      "prism-beam"
    ],
    "description": "Floating amethysts orbit its skull, refracting its thoughts into raw force.",
    "spriteKey": "blippet-amerex",
    "sprites": {
      "front": "blippets/004_amerex_psychic-crystal.png"
    }
  },
  {
    "dex": 5,
    "slug": "silfing",
    "name": "Silfing",
    "types": [
      "water",
      "dragon"
    ],
    "baseStats": {
      "hp": 65,
      "atk": 60,
      "def": 55,
      "spAtk": 70,
      "spDef": 70,
      "spd": 60
    },
    "rarity": "uncommon",
    "abilities": [
      "torrent",
      "serene-grace"
    ],
    "learnset": [
      {
        "level": 1,
        "moveId": "water-gun"
      },
      {
        "level": 1,
        "moveId": "twister"
      },
      {
        "level": 7,
        "moveId": "bubble-beam"
      },
      {
        "level": 13,
        "moveId": "dragon-breath"
      }
    ],
    "movePool": [
      "water-gun",
      "twister",
      "bubble-beam",
      "dragon-breath"
    ],
    "description": "A juvenile dragon of shallow lagoons. Hums when content.",
    "spriteKey": "blippet-silfing",
    "sprites": {
      "front": "blippets/005_silfing_water-dragon.png"
    }
  }
];
